### ISSUE TITLE
Origin file

### ISSUE THREAD

**Issue by simake** [Wire-Flies/PostgresSQLInserterCXX#2]
If we want to be able to use an RNN for the AI module, it will be necessary to be able to tell from which file and in which order each position came. Is this currently possible? :)

If not, don't sweat it. We'll start with a standard autoencoder either way.

**Comment by jvikstrom** [comment]
?
I don't undestand the questions, how does what file something is in matter in any way?
To get the positions for a flight you do a join on flight_id, and for the order of the positions you order by snapshot_id in flight_data. (I think snapshot_id is the timestamp the data was captured)

**Comment by simake** [comment]
Each file represents the flight route for one day, making it a very manageable format to work with, but you're right. That information can be extracted from the snapshot_id too, it's just that the snapshot_id is the
> time of sample in seconds since 1 Jan 1970 00:00:00 UTC

and not the actual date.

**Comment by simake** [comment]
It's not a problem though: [https://dba.stackexchange.com/a/61345](https://dba.stackexchange.com/a/61345)
